import type { GoalSnapshot } from '../types/domain'

export const mockSnapshot: GoalSnapshot = {
  source: 'mock',
  metrics: [
    {
      label: 'Mediateurs actifs',
      value: '12',
      detail: '9 deja affectes sur la plage 14h-19h',
    },
    {
      label: 'Vehicules exploitables',
      value: '6',
      detail: 'Capacite verrouillee a 2 mediateurs maximum',
    },
    {
      label: 'Feuilles pretes',
      value: '8',
      detail: '2 brouillons attendent arbitrage',
    },
    {
      label: 'Dernier import GTFS',
      value: '30/03',
      detail: 'Fenetre T2C valide jusqu au 26/06/2026',
    },
  ],
  mediators: [
    {
      id: 'med-1',
      fullName: 'Nadia Belkacem',
      sector: 'Jaude',
      canDrive: true,
      status: 'assigned',
      preferredWindow: '13:30 - 20:00',
    },
    {
      id: 'med-2',
      fullName: 'Romain Couthon',
      sector: 'Chamalieres',
      canDrive: true,
      status: 'assigned',
      preferredWindow: '14:00 - 19:30',
    },
    {
      id: 'med-3',
      fullName: 'Sonia Perret',
      sector: 'Lempdes',
      canDrive: false,
      status: 'assigned',
      preferredWindow: '15:00 - 21:00',
    },
    {
      id: 'med-4',
      fullName: 'Mathieu Roche',
      sector: 'Cournon',
      canDrive: true,
      status: 'available',
      preferredWindow: '16:00 - 22:00',
    },
  ],
  vehicles: [
    {
      id: 'veh-1',
      label: 'Clio 1',
      maxMediators: 2,
      assignedMediators: 2,
      status: 'ready',
      area: 'Nord',
    },
    {
      id: 'veh-2',
      label: '208 3',
      maxMediators: 2,
      assignedMediators: 2,
      status: 'ready',
      area: 'Centre',
    },
    {
      id: 'veh-3',
      label: 'Kangoo 2',
      maxMediators: 2,
      assignedMediators: 1,
      status: 'draft',
      area: 'Sud',
    },
    {
      id: 'veh-4',
      label: 'C3 5',
      maxMediators: 2,
      assignedMediators: 0,
      status: 'issue',
      area: 'Reserve atelier',
    },
  ],
  roadmaps: [
    {
      id: 'road-1',
      title: 'Rotation Tram A / Centre',
      line: 'A',
      origin: 'Champratel',
      destination: 'La Pardieu Gare',
      departure: '14:10',
      arrival: '17:30',
      vehicleLabel: '208 3',
      mediatorNames: ['Nadia Belkacem', 'Sonia Perret'],
      occupancy: 2,
      progress: 88,
      status: 'ready',
    },
    {
      id: 'road-2',
      title: 'Bus B / Axe Nord',
      line: 'B',
      origin: 'Stade G. Montpied',
      destination: 'Royat Pepiniere',
      departure: '15:00',
      arrival: '18:15',
      vehicleLabel: 'Clio 1',
      mediatorNames: ['Romain Couthon', 'Mathieu Roche'],
      occupancy: 2,
      progress: 72,
      status: 'ready',
    },
    {
      id: 'road-3',
      title: 'Jaude / renfort sortie scolaire',
      line: 'E1',
      origin: 'Jaude',
      destination: 'Lycee Lafayette',
      departure: '16:05',
      arrival: '18:40',
      vehicleLabel: 'Kangoo 2',
      mediatorNames: ['Mathieu Roche'],
      occupancy: 1,
      progress: 55,
      status: 'draft',
      risk: '1 mediateur manquant pour couvrir le retour 18:10.',
    },
  ],
  alerts: [
    {
      id: 'alert-1',
      tag: 'Capacite',
      title: 'Kangoo 2 part avec une place libre',
      description: 'La feuille Jaude / renfort scolaire n a qu un seul mediateur assigne.',
    },
    {
      id: 'alert-2',
      tag: 'GTFS',
      title: 'Prevoir un nouvel import avant le 26/06/2026',
      description: 'La validite publiee du dernier feed T2C se termine le 26 juin 2026.',
    },
    {
      id: 'alert-3',
      tag: 'Contrainte',
      title: 'Aucun vehicule supplementaire disponible cote sud',
      description: 'La reserve atelier doit etre levee pour absorber une nouvelle feuille tardive.',
    },
  ],
  gtfsImportCount: 1,
}
